---
- name: Update and reboot
  hosts: "*"
  become: true
  gather_facts: yes
  tasks:
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest

    - name: Reboot servers
      reboot:
        pre_reboot_delay: 90
        msg! "!!!Attention, server will be rebooted in 90 seconds!!!"
